source 'https://rubygems.org'
gem 'better_errors',      '~> 2.1.1'
gem 'binding_of_caller',  '~> 0.7.2'
gem 'json',               '~> 1.8.3'
gem 'pry',                '~> 0.10.3'
gem 'pry-nav',            '~> 0.2.4'
gem 'sinatra',            '~> 1.4.6'
gem 'sqlite3',            '~> 1.3.11'
gem 'twitter',            '~> 5.15'
